[PE188-18] Integrate Erp Order Cancellation
Departamento-TI/cenabast-tienda pull request #89
Opened 2024-04-15 21:28 UTC by LeonardoSantis-AcidLabs

## Link to Issue(s) in JIRA:
- https://linets.atlassian.net/browse/PE188-18

## Description

- Add order cancel ERP service, integrated to after cancel of an Spree::Order
- Canceller service linked with SaleOrder#cancel_in_erp! method,
  - This calls a CancelSaleOrderInErp ActiveJob and related service, which update the model based on the response of the request
- Add #nullify action to SaleOrderController in admin to allo cance/nullify one sale order in particular with a button in sale orders.
  - Added cancellation_pending status to sale order to mark this
- Add related specs

## Checklist

Before you move on, make sure that:

- [ ] No unintended changes are included
- [ ] Spelling is correct
- [ ] There are tests covering new/changed functionality
- [ ] Rubocop style is passing, and Rspec tests are passing.
- [ ] Documentation has been written (Docs or code)
- [ ] Commits have meaningful names and changes. _CR remarks_-like commits are squashed.
- [ ] Proper labels assigned. Use `WIP` label to indicate that state

2024-04-15 21:38 UTC, LeonardoSantis-AcidLabs commented
Buenas @FelipeFabio-Acid , tengo pendiente crear algo de documentación de la feature, pero el resto de la feature ya está terminada.

2024-04-16 02:33 UTC, ext-ffabio-esb reviewed
muy buen PR 👏 
Dejé un review de un campo de la respuesta del API al crear la orden, que se podría atacar en este PR, para cerrar la creación y anulación.

2024-04-16 02:33 UTC, ext-ffabio-esb commented on app/services/cenabast/spree/erp/sale_orders/send_to_erp.rb
en la línea 47 hay que editar el campo, la respuesta actual del servicio responde con la key `pedidoVentaSapId`.
Tampoco ahora viene en la respuesta el campo: `pedidoId`.

2024-04-16 02:36 UTC, FelipeFabio-Acid requested changes
muy buen PR 👏
Dejé un review de un campo de la respuesta del API al crear la orden, que se podría atacar en este PR, para cerrar la creación y anulación.

2024-04-16 02:36 UTC, FelipeFabio-Acid commented on app/services/cenabast/spree/erp/sale_orders/send_to_erp.rb
> +        # Service that takes an existing SaleOrder model and sends it to the ERP.
en la línea 47 hay que editar el campo, la respuesta actual del servicio responde con la key `pedidoVentaSapId`.
Tampoco ahora viene en la respuesta el campo: `pedidoId`.

2024-04-16 18:44 UTC, merged